In [1]:
import numpy as np
from numpy.linalg import norm

import logging


from lambert_izzo import lambert, izzo

In [2]:
logging.basicConfig(level=logging.DEBUG)

In [3]:
r1 = np.array([5000, 10000, 2100])
r2 = np.array([-14600, 2500, 7000])

# time of flight [s]
tof = 36000

# gravitational parameter [km^3/s^2]
mu = 398600

In [4]:
sol=izzo(mu, r1, r2, tof, M=1, numiter=35, rtol=1e-8)

In [5]:
sol

<generator object izzo at 0x108864518>

In [6]:
for s in sol:
    print(s)

(array([-1.73973544,  5.71578771,  3.07852676]), array([ 2.31455213, -3.54538859, -2.41424268]))
(array([-6.17521058,  1.78753536,  3.26318269]), array([-3.53832153, -4.23588896, -0.30928801]))


In [7]:
sol = lambert(mu, r1, r2, tof, M=1, numiter=35, rtol=1e-8)

In [8]:
sol

(array([-1.73973544,  5.71578771,  3.07852676]),
 array([ 2.31455213, -3.54538859, -2.41424268]))