In [1]:
import numpy as np
import scipy as sp
import pandas as pd
import scipy.optimize as opt
from numpy import linalg as linalg
from numpy.linalg import norm

from satellite import Satellite
from asteroid import Asteroid

In [2]:
ep0 = 54000
ep1 = 54003
earth = Asteroid('Earth',ep0,0.999988049532578, 1.671681163160e-2, 0.8854353079654e-3, 175.40647696473, 287.61577546182, 257.60683707535)
print(earth.details())

*Asteroid Earth*
  Epoch0 (MJD)  : 54000
  a (AU)        : 0.9999880495325779
  e_mag         : 0.0167168116316
  i (deg)       : 0.0008854353079653999
  LAN (deg)     : 175.40647696473
  argPeri (deg) : 287.61577546182
  meanAnom (deg): 257.60683707535


In [3]:
sat = Satellite()

In [4]:
sat.set_state(ep0,*earth.get_rv(epoch = ep0))

In [5]:
sat

Spacecraft Scaramouche

In [6]:
print(sat.details())

*Spacecraft Scaramouche*
  Epoch0 (MJD)  : 54000
  a (AU)        : 0.9999880495325777
  e_mag         : 0.016716811631599663
  i (deg)       : 0.0008854353079653586
  LAN (deg)     : 175.40647696473007
  argPeri (deg) : 287.6157754618199
  meanAnom (deg): 31.45418029906358


In [7]:
print(earth.details())

*Asteroid Earth*
  Epoch0 (MJD)  : 54000
  a (AU)        : 0.9999880495325779
  e_mag         : 0.0167168116316
  i (deg)       : 0.0008854353079653999
  LAN (deg)     : 175.40647696473
  argPeri (deg) : 287.61577546182
  meanAnom (deg): 257.60683707535


In [8]:
earth2 = Asteroid('Earth2',sat.epoch, sat.a/sat.u_AU, sat.e_mag, sat.i*180/np.pi, sat.LAN*180/np.pi, sat.omega*180/np.pi, sat.M0*180/np.pi)
earth2

Asteroid Earth2

In [9]:
print(earth2.details())

*Asteroid Earth2*
  Epoch0 (MJD)  : 54000
  a (AU)        : 0.9999880495325777
  e_mag         : 0.016716811631599663
  i (deg)       : 0.0008854353079653586
  LAN (deg)     : 175.4064769647301
  argPeri (deg) : 287.61577546181996
  meanAnom (deg): 31.45418029906358


In [10]:
sat.r, sat.v

(array([-1.05175505e+08,  1.03376966e+08, -1.46226274e+03]),
 array([-2.13667714e+01, -2.13571049e+01,  3.55431706e-04]))

In [11]:
earth.get_rv(ep0)

(array([-1.05175505e+08,  1.03376966e+08, -1.46226274e+03]),
 array([-2.13667714e+01, -2.13571049e+01,  3.55431706e-04]))

In [12]:
earth2.get_rv(ep0)

(array([-1.35975996e+08, -6.35094672e+07,  1.14659612e+03]),
 array([ 1.21209819e+01, -2.71024246e+01,  4.02487747e-04]))

In [13]:
earth.get_meanAnom(ep0)*180/np.pi

257.60683707535

In [14]:
earth.get_meanAnom(ep0), sat.M0

(4.496087482613457, 0.5489790097345941)

In [15]:
earth.get_eccAnom(ep0), sat.eccAnom

(4.479820726328422, 0.5578279650154122)

In [16]:
(earth.get_trueAnom(ep0), sat.theta)

(0.5667406874773921, 0.5667406874773927)

In [17]:
er, ev = earth.get_rv(ep0)

In [18]:
np.cross(er, ev)

array([5.51375256e+03, 6.86265430e+04, 4.45507628e+09])

In [19]:
sat.h

array([5.51375256e+03, 6.86265430e+04, 4.45507628e+09])

In [20]:
earth.get_eccAnom(ep0)+ sat.eccAnom

5.0376486913438345

In [21]:
earth.get_eccAnom(ep0)*180/np.pi, sat.eccAnom*180/np.pi

(256.6748205938496, 31.961188089754458)

In [22]:
earth.get_eccAnom(ep0), sat.get_eccAnom(ep0)

(4.479820726328422, 0.5578279650154123)

In [23]:
earth.get_meanAnom(ep0), sat.get_meanAnom(ep0)

(4.496087482613457, 0.5489790097345941)

In [24]:
print(earth.get_r(epoch=ep0))
print(earth.get_v(epoch=ep0))
print()

[-1.05175505e+08  1.03376966e+08 -1.46226274e+03]
[-2.13667714e+01 -2.13571049e+01  3.55431706e-04]



In [25]:
sat.get_r(epoch=ep0)

array([-1.35975996e+08, -6.35094672e+07,  1.14659612e+03])