In [1]:
import numpy as np
import poliastro as pa
from lambert_izzo import lambert

from poliastro.core import iod
from poliastro.iod import izzo

In [2]:
# verifying against the example in the docs:
# http://docs.poliastro.space/en/stable/examples/Revisiting%20Lamberts%20problem%20in%20Python.html
from astropy import units as u

from poliastro.bodies import Earth

In [3]:
k_ = Earth.k
r0 = np.array([15945.34, 0.0, 0.0])
r0_ = r0 * u.km
r = np.array([12214.83399, 10249.46731, 0.0])
r_ = r * u.km
tof = 76*60
tof_ = tof * u.second

expected_va  = np.array([2.058925, 2.915956, 0.0])
expected_va_ = expected_va * u.km / u.s
expected_vb  = np.array([-3.451569, 0.910301, 0.0])
expected_vb_ = expected_vb * u.km / u.s

(v0_, v_), = izzo.lambert(k_, r0_, r_, tof_)
print(v0_, v_)

[2.05891257 2.91596459 0.        ] km / s [-3.4515665   0.91031354  0.        ] km / s


In [4]:
k = Earth.k.to(u.km**3/u.s**2).value

In [5]:
np.cross(r0, r)

array([0.00000000e+00, 0.00000000e+00, 1.63431241e+08])

In [6]:
lambert(k, r0, r, tof)

(array([2.05891257, 2.91596459, 0.        ]),
 array([-3.4515665 ,  0.91031354,  0.        ]))

In [7]:
r0 = np.array([5000.0, 10000.0, 2100.0])
r0_ = r0 * u.km
r = np.array([-14600.0, 2500.0, 7000.0])
r_ = r * u.km
tof = 60*60
tof_ = 1.0 * u.h

expected_va = [-5.9925, 1.9254, 3.2456] * u.km / u.s
expected_vb = [-3.3125, -4.1966, -0.38529] * u.km / u.s

(v0, v), = izzo.lambert(k_, r0_, r_, tof_)
print(v0, v)

[-5.99249502  1.92536671  3.24563805] km / s [-3.3124585  -4.19661901 -0.38528906] km / s


In [8]:
lambert(k, r0, r, tof)

(array([-5.99249502,  1.92536671,  3.24563805]),
 array([-3.3124585 , -4.19661901, -0.38528906]))

In [9]:
r0 = np.array([22592.145603, -1599.915239, -19783.950506])
r0_ = r0* u.km
r = np.array([1922.067697, 4054.157051, -8925.727465])
r_ = r * u.km
tof_ = 10 * u.h
tof = (tof_.to(u.s)).value

expected_va = [2.000652697, 0.387688615, -2.666947760] * u.km / u.s
expected_vb = [-3.79246619, -1.77707641, 6.856814395] * u.km / u.s

expected_va_l = [0.50335770, 0.61869408, -1.57176904] * u.km / u.s
expected_vb_l = [-4.18334626, -1.13262727, 6.13307091] * u.km / u.s

expected_va_r = [-2.45759553, 1.16945801, 0.43161258] * u.km / u.s
expected_vb_r = [-5.53841370, 0.01822220, 5.49641054] * u.km / u.s

In [14]:
# zero rev
(v0, v), = izzo.lambert(k_, r0_, r_, tof_, M=0)
print(v0, v)

lambert(k, r0, r, tof, M=0, return_='all')

[ 2.0006527   0.38768862 -2.66694776] km / s [-3.79246619 -1.77707641  6.85681439] km / s


[(array([ 2.0006527 ,  0.38768862, -2.66694776]),
  array([-3.79246619, -1.77707641,  6.85681439]))]

In [19]:
# single rev
sols = izzo.lambert(k_, r0_, r_, tof_, M=1)

for s in sols:
    print(s)
    
lambert(k, r0, r, tof, M=1, return_='all')

(<Quantity [ 0.5033577 ,  0.61869408, -1.57176904] km / s>, <Quantity [-4.18334626, -1.13262727,  6.13307091] km / s>)
(<Quantity [-2.45759553,  1.16945801,  0.43161258] km / s>, <Quantity [-5.53841318,  0.01822213,  5.49641016] km / s>)


[(array([ 0.5033577 ,  0.61869408, -1.57176904]),
  array([-4.18334626, -1.13262727,  6.13307091])),
 (array([-2.45759553,  1.16945801,  0.43161258]),
  array([-5.53841318,  0.01822213,  5.49641016]))]